name: AntiPluginStealer
version: 1.1
main: dev.imptovskii.aps.Main
depend: [ProtocolLib]
authors: [Imptovskii]
description: this plugin to prevent hacked clients from seeing the server plugins

commands:
  apsreload: